name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    # The analysis requires to retrieve dependencies and build successfully
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.3'  # Adjust to used Flutter version

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get
      working-directory: example

    # Build the web app
    - name: Build Flutter Web
      run: flutter build web --release --base-href /theme_provider/
      working-directory: example
      
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@v5
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
