name: Build and Deploy Flutter Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Flutter environment
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0'  # Adjust to used Flutter version

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Build the web app
    - name: Build Flutter Web
      run: flutter build web --release --web-renderer html --target example/lib/main.dart

    # Deploy to gh-pages branch
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: example/build/web
        # deploy to gh-pages branch
        branch: gh-pages
        force_orphan: true  # Create an orphan branch to keep it separate
